### ISSUE TITLE
Add 4.x branch

### ISSUE THREAD

**Issue by tetrapod00** [paddy-exe/Godot-RealTimeCaustics#1]
I believe I have the shader converted for version 4.x. I still need to do some testing to make sure I didn't break anything.

I'd like to merge this in, but I think you might have to add a `4.x` branch first? I'm not sure how to merge in an entire new branch from a PR, if it's possible at all.

Up to you whether to call the new branch `4.x`, `4.3`, or `main`/`master`. Once the branch is up I can PR against it sometime today or tomorrow, and if you want to review the exact changes you're welcome to

---

![Godot_v4 3-stable_win64_7sBpMp6tvp](https://github.com/user-attachments/assets/b3adc2ca-42d0-483a-add9-ca8c774161ad)

- Works in Forward+, Compatibility, and Mobile.
- Adjusted shader to work in 4.x. I have only tested in 4.3, but it looks like reverse-z doesn't actually affect this, so it might work in 4.2 as well. If it's all the same to you, 4.3 can be the minimum version. If not, I can try testing in 4.2 (and maybe 4.1?). 
- Cleaned up the shader, removing unneeded matrix varyings.
- Fixed the rotation behavior at certain angles. At least, it looks better to my eyes? Some of your original matrix math is a little beyond me.
- Fixed at least one precision bug, causing pixelated caustics due to `mediump`. There is a lot of `mediump` left, and the caustics still maybe have some banding/precision issues if you zoom in, but it looks generally fine. If I tackle that it should be in a followup commit.
- Added some sliders for the caustics parameters. Changed the shader default values to match the look of the existing tweaked values. Sliders are set to powers of two where possible, and the range is set as what looks nice artistically + one more power of two in either direction:
![Godot_v4 3-stable_win64_6dqlAF8TrH](https://github.com/user-attachments/assets/97ca90d3-ceb1-44da-90c9-ce7a8ec45a27)

- I did *not* rename variables much. My preferred naming convention for shaders that get shared is more verbose, but I didn't want to change too much for no reason.

**Comment by tetrapod00** [comment]
Still working out some edge cases, actually. The lighting function in 4.x seemed to change, so I can't use the same setup of ALBEDO and `render_mode` as in 3.x, and I haven't found the right setup in 4.x. I keep getting a dim outline of the bounding box.

Also: OmniLights? It looks like the original unity shader supports a single directional light, passed in. Your 3.5 version supports multiple directional lights, by using LIGHT in the light() function. Was your original version ever meant to work with omni lights? The shader doesn't check to see if the LIGHT is directional, which produces funny results with omni lights.
![Godot_v4 3-stable_win64_qvJ2fVMSu4](https://github.com/user-attachments/assets/14a61dff-c869-42d8-aec3-0f90fc841364)

I imagine this could be dealt with in userspace just by using a specific cull mask for the caustics lights. But I can also use `LIGHT_IS_DIRECTIONAL` to only apply the shader to directional lights.

Thanks for any guidance, I also understand if you don't want to think too much about a two year old codebase

**Comment by paddy-exe** [comment]
Hey @tetrapod00! Thank you so much for doing this :D now regarding the branch: I have created a `4.3+` branch now you can make a PR against. I definitely appreciate it that you took the time for this. Regarding your changes: They look really great and I would be happy to review it. About the OmniLight support: There was never any support planned. Not really sure if it is even possible to make it look nice.

**Comment by tetrapod00** [comment]
Yeah, happy to help update this. I thought about doing it when I converted the shader the first time, but once I had to do it twice it should just be done as a PR.

**Comment by paddy-exe** [comment]
Closing as of #2 being merged now. Thanks again for your work on this!
